### ISSUE TITLE
deployment on gitpages

### ISSUE THREAD

**Issue by seo2im** [seo2im/portfolio#20]
## Description
deployment of git pages

### Todo
- [x] merge development to master
- [ ] gh-pages to master
- [ ] set git action CD
