### ISSUE TITLE
make Project page component

### ISSUE THREAD

**Issue by seo2im** [seo2im/portfolio#30]
## Description
make Project page for each project common source

### Todo
- [ ] set default design
- [ ] router? inside page?
- [ ] how to show contents of it(writing paragrah...)

**Comment by seo2im** [comment]
https://www.figma.com/file/eErjt6o1PA5rxCwsaiyvdl/Portfolio-Design?node-id=0%3A1
