### ISSUE TITLE
re-design main page

### ISSUE THREAD

**Issue by seo2im** [seo2im/portfolio#31]
## Description
change main page source & design

### Todo
- [ ] re-design What content in
- [ ] set drag & drop styling
- [ ] make background svg
- [ ] make pin svg
