### ISSUE TITLE
re-design Project Page

### ISSUE THREAD

**Issue by seo2im** [seo2im/portfolio#35]
## Description
re-designing

### Todo
- [x] set spec of project
- [x] set work contents
- [x] review
- [x] etc => other page of project
