### ISSUE TITLE
set each bug fix

### ISSUE THREAD

**Issue by seo2im** [seo2im/portfolio#37]
## Description
bug fix

### Todo
- [x] first page with localstorage
- [ ] carrousel bug(when first back not work animation
- [ ] fouc (dom load)

**Comment by seo2im** [comment]
dont know two is why
