### ISSUE TITLE
re design main again...

### ISSUE THREAD

**Issue by seo2im** [seo2im/portfolio#46]
## Description
set main re design
https://www.figma.com/file/eErjt6o1PA5rxCwsaiyvdl/Portfolio-Design?node-id=0%3A1

### Todo
- [x] set board text & photo box
- [x] set postit animation
- [x] set nav to my skill
- [x] write "dragable postit!"
