### ISSUE TITLE
set Project Page content each project

### ISSUE THREAD

**Issue by seo2im** [seo2im/portfolio#49]
## Description
make content of project

### Todo
- [ ] explain each section
- [ ] link each section
- [ ] scroll spy need?
