### ISSUE TITLE
re-design main page too

### ISSUE THREAD

**Issue by seo2im** [seo2im/portfolio#50]
## Description
redesign because contents changed 

https://www.notion.so/eb808513140149f38961fcc140beddf4

### Todo
- [x] set postit completly re-compose module
- [ ] main page change animation setting in message pool
- [ ] project page maybe deleted...?
